Bibi/elife v2
everlifeai/everlife-community-node pull request #31
Opened 2021-04-09 19:15 UTC by Bibitha-V

2021-04-10 12:26 UTC, theproductiveprogrammer requested changes

2021-04-10 12:26 UTC, theproductiveprogrammer commented on package.json
> +    "ethereumjs-wallet": "^1.0.1",
Why do we need this?

2021-04-12 05:00 UTC, Bibitha-V commented on package.json
> +    "ethereumjs-wallet": "^1.0.1",
This package we are not using now.

2021-04-12 12:23 UTC, theproductiveprogrammer approved these changes

2021-04-12 12:23 UTC, merged